// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace QAssetBundle
{
    
    public class Assetobj_prefab
    {
        public const string BundleName = "ASSETOBJ_PREFAB";
        public const string ASSETOBJ = "ASSETOBJ";
    }
    public class Music
    {
        public const string BundleName = "MUSIC";
        public const string BOSS = "BOSS";
        public const string CITY2 = "CITY2";
        public const string CLINIC = "CLINIC";
        public const string GHOST = "GHOST";
        public const string MAGIC = "MAGIC";
        public const string MENU = "MENU";
        public const string PUZZLE = "PUZZLE";
        public const string RETRO3 = "RETRO3";
        public const string RETRO4 = "RETRO4";
        public const string SPEED = "SPEED";
        public const string VILLAGE = "VILLAGE";
        public const string VILLAGE2 = "VILLAGE2";
        public const string WATER = "WATER";
    }
    public class Sounds
    {
        public const string BundleName = "SOUNDS";
        public const string CLICK = "CLICK";
        public const string HIT = "HIT";
        public const string PASS_LEVEL = "PASS_LEVEL";
        public const string RAIN_HEAVY = "RAIN_HEAVY";
        public const string TYPING = "TYPING";
    }
    public class Spriteatlas_spriteatlas
    {
        public const string BundleName = "SPRITEATLAS_SPRITEATLAS";
        public const string SPRITEATLAS = "SPRITEATLAS";
    }
    public class Uiaboutpanel_prefab
    {
        public const string BundleName = "UIABOUTPANEL_PREFAB";
        public const string UIABOUTPANEL = "UIABOUTPANEL";
    }
    public class Uiconnect_prefab
    {
        public const string BundleName = "UICONNECT_PREFAB";
        public const string UICONNECT = "UICONNECT";
    }
    public class Uigameoverpanel_prefab
    {
        public const string BundleName = "UIGAMEOVERPANEL_PREFAB";
        public const string UIGAMEOVERPANEL = "UIGAMEOVERPANEL";
    }
    public class Uigamepanel_prefab
    {
        public const string BundleName = "UIGAMEPANEL_PREFAB";
        public const string UIGAMEPANEL = "UIGAMEPANEL";
    }
    public class Uigamepausepanel_prefab
    {
        public const string BundleName = "UIGAMEPAUSEPANEL_PREFAB";
        public const string UIGAMEPAUSEPANEL = "UIGAMEPAUSEPANEL";
    }
    public class Uihomepanel_prefab
    {
        public const string BundleName = "UIHOMEPANEL_PREFAB";
        public const string UIHOMEPANEL = "UIHOMEPANEL";
    }
    public class Uimsg_prefab
    {
        public const string BundleName = "UIMSG_PREFAB";
        public const string UIMSG = "UIMSG";
    }
    public class Uistorypanel_prefab
    {
        public const string BundleName = "UISTORYPANEL_PREFAB";
        public const string UISTORYPANEL = "UISTORYPANEL";
    }
    public class Uitestunirx_prefab
    {
        public const string BundleName = "UITESTUNIRX_PREFAB";
        public const string UITESTUNIRX = "UITESTUNIRX";
    }
    public class Uitrainmodepanel_prefab
    {
        public const string BundleName = "UITRAINMODEPANEL_PREFAB";
        public const string UITRAINMODEPANEL = "UITRAINMODEPANEL";
    }
    public class Uitrainoverpanel_prefab
    {
        public const string BundleName = "UITRAINOVERPANEL_PREFAB";
        public const string UITRAINOVERPANEL = "UITRAINOVERPANEL";
    }
}
