// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace QAssetBundle
{
    
    public class Assetobj_prefab
    {
        public const string BundleName = "ASSETOBJ_PREFAB";
        public const string ASSETOBJ = "ASSETOBJ";
    }
    public class Sounds
    {
        public const string BundleName = "SOUNDS";
        public const string HIT = "HIT";
    }
    public class Spriteatlas_spriteatlas
    {
        public const string BundleName = "SPRITEATLAS_SPRITEATLAS";
        public const string SPRITEATLAS = "SPRITEATLAS";
    }
    public class Uiconnect_prefab
    {
        public const string BundleName = "UICONNECT_PREFAB";
        public const string UICONNECT = "UICONNECT";
    }
    public class Uigameoverpanel_prefab
    {
        public const string BundleName = "UIGAMEOVERPANEL_PREFAB";
        public const string UIGAMEOVERPANEL = "UIGAMEOVERPANEL";
    }
    public class Uigamepanel_prefab
    {
        public const string BundleName = "UIGAMEPANEL_PREFAB";
        public const string UIGAMEPANEL = "UIGAMEPANEL";
    }
    public class Uigamepausepanel_prefab
    {
        public const string BundleName = "UIGAMEPAUSEPANEL_PREFAB";
        public const string UIGAMEPAUSEPANEL = "UIGAMEPAUSEPANEL";
    }
    public class Uihomepanel_prefab
    {
        public const string BundleName = "UIHOMEPANEL_PREFAB";
        public const string UIHOMEPANEL = "UIHOMEPANEL";
    }
    public class Uimsg_prefab
    {
        public const string BundleName = "UIMSG_PREFAB";
        public const string UIMSG = "UIMSG";
    }
    public class Uitestunirx_prefab
    {
        public const string BundleName = "UITESTUNIRX_PREFAB";
        public const string UITESTUNIRX = "UITESTUNIRX";
    }
}
